### ISSUE TITLE
is there anyway to capture all frames?

### ISSUE THREAD

**Issue by preetparm** [tawaship/CanvasRecorder#3]
hi, i tried to record animation of 32 secoonds, but recording comes out with only 28 second. is ther anyway to capture whole time, doesnt matter if somthing drawn on canvas or not?

**Comment by tawaship** [comment]
Hi.

It doesn't matter if something is drawn on the canvas or not.
This recorder captures the canvas from the moment you call `recorder.start()` to the moment you call `recorder.finishAsync()`.

How does the 28-second recorded video look different from the original 32-second animation?
(The beginning or end is missing, the playback speed is fast, etc.)

**Comment by preetparm** [comment]
hi budy,  i have timer in my application, because i am wants to record 32 second video  hence i set 32000 value in setTimeout function.however video downloaded  when 28 second triggered on timer. might be some bugs in my code.

**Comment by tawaship** [comment]
`setTimeout` is not guaranteed to execute after the specified number of milliseconds.
(However, it is a little unnatural behavior that there is a difference of 4 seconds ...)

If you want the recording to end at a more precise time, you need to somehow get the timing at which the animation recording should end, and execute `recorder.finishAsync()` at that timing.
- If you are the author of the animation, insert the code at the end of the animation
- Manually execute code after visually confirming animation completion
